apiVersion: apps/v1
kind: Deployment
metadata:
  name: mymoneyapp
spec:
  selector:
    matchLabels:
      app: mymoneyapp
  replicas: 1
  template:
    metadata:
      labels:
        app: mymoneyapp
    spec:
      containers:
        - name: mymoneyapp
          image: nityanandgaonkar/ngaonkar:latest
          ports:
            - containerPort: 8080
          env:   # Setting Enviornmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              valueFrom :
                configMapKeyRef :
                  name : db-config
                  key :  host

            - name: DB_NAME  # Setting Database name from configMap
              valueFrom :
                configMapKeyRef :
                  name : db-config
                  key :  dbName

            - name: DB_USERNAME  # Setting Database username from Secret
              valueFrom :
                secretKeyRef :
                  name : mysql-secrets
                  key :  username

            - name: DB_PASSWORD # Setting Database password from Secret
              valueFrom :
                secretKeyRef :
                  name : mysql-secrets
                  key :  password

            - name: SPRING_KAFKA_BOOTSTRAPSERVERS
              value: "kafka:29092"
            - name: ACC_TOPIC_NAME
              value: "accounttopic"
            - name: TXN_TOPIC_NAME
              value: "txntopic"
            - name: PROPERTIES_FILE
              value: "application.properties"

---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: mymoneyapp-svc
spec:
  selector:
    app: mymoneyapp
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 80 # The port exposed by the service
  type: NodePort # type of the service.
