---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mymoneyapp
  namespace: developement
  labels:
    app: mymoneyapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mymoneyapp
  template:
    metadata:
      labels:
        app: mymoneyapp
    spec:
      containers:
        - name: mymoneyapp
          image: nityanandgaonkar/ngaonkar:latest
          env:
            - name: SPRING_KAFKA_BOOTSTRAPSERVERS
              value: "localhost:9092"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql:3306/mymoney_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "root"
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
